server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/jefta1986/config-repo.git
#          searchPaths: userservice
#          username: Artuwok
#          password: Civilization1986
          timeout: 10
          force-pull: true