server:
  port: 8081

spring:
  application:
    name: data
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5


#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    registerWithEureka: false
#    fetchRegistry: false
#  instance:
#    preferIpAddress: true