server:
  port: 8081

spring:
  application:
    name: data

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5


#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    registerWithEureka: false
#    fetchRegistry: false
#  instance:
#    preferIpAddress: true