spring:
  application:
    name: discovery
#  cloud:
#    config:
#      name: eureka
#      uri: http://localhost:8888

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false