spring:
  application:
    name: eureka
  cloud:
    config:
      name: eureka
#      uri: http://localhost:8888

server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: localhost