server:
  port: 8082

spring:
  application:
    name: gateway

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5


#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    registerWithEureka: false
#    fetchRegistry: false
#  instance:
#    preferIpAddress: true

#  spring
#  data
#  mongodb
#authentication-database: admin
#username: root
#password: root
#database: test_db
#port: 27017
#host: localhost