server:
  port: 8082

spring:
  application:
    name: gateway

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

zuul:
  routes:
    discovery:
        path: /eureka/**
        sensitive-headers: Set-Cookie,Authorization
        url: http://localhost:8082
    data:
      path: /books/**
      sensitive-headers: Set-Cookie,Authorization

hystrix:
  command:
    data:
      execution:
        isolation:
          thread.:
            timeoutInMilliseconds: 600000
    discovery:
      execution:
        isolation:
          thread.:
            timeoutInMilliseconds: 600000


#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    registerWithEureka: false
#    fetchRegistry: false
#  instance:
#    preferIpAddress: true